$script = <<SCRIPT
echo '=====> Installing git'
dnf install -y git
echo '=====> Clone https://github.com/troppens/ansible-mylinux'
git clone https://github.com/troppens/ansible-mylinux /root/mylinux
echo '=====> Enable EPEL repo (required for Ansible)'
dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
echo '=====> Installing ansible'
dnf install -y ansible
echo '=====> Update RPMs'
dnf update -y
echo '====> Shutdown server'
shutdown -h now
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.provision "shell", inline: $script

  # DNS Not Working
  # https://www.vagrantup.com/docs/virtualbox/common-issues.html
  # https://serverfault.com/questions/453185/vagrant-virtualbox-dns-10-0-2-3-not-working
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

end
