$script = <<SCRIPT
echo '=====> Installing cloud utils'
dnf install -y cloud-utils-growpart
echo '=====> Grow partition which contains root fs'
growpart /dev/sda 1
echo '=====> Grow root fs'
xfs_growfs /
echo '=====> Installing git'
dnf install -y git
echo '=====> Clone https://github.com/troppens/ansible-mylinux'
git clone https://github.com/troppens/ansible-mylinux /root/mylinux
echo '=====> Enable EPEL repo (required for Ansible)'
dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
echo '=====> Installing ansible'
dnf install -y ansible
echo '=====> Configure root ssh to localhost'
ssh-keygen -b 4096 -P "" -f /root/.ssh/id_rsa
touch /root/.ssh/known_hosts
chmod 600 /root/.ssh/known_hosts
ssh-keyscan localhost >> /root/.ssh/known_hosts
touch /root/.ssh/authorized_keys
chmod 600 /root/.ssh/authorized_keys
cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
echo '=====> Update RPMs'
dnf update -y
echo '====> Shutdown server'
shutdown -h now
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.disksize.size = '20GB'
  config.vm.provision "shell", inline: $script

  # DNS Not Working
  # https://www.vagrantup.com/docs/virtualbox/common-issues.html
  # https://serverfault.com/questions/453185/vagrant-virtualbox-dns-10-0-2-3-not-working
  config.vm.provider :virtualbox do |vb|
    vb.memory = 4096
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

end
